name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
  # habilitar o gatilho manual atraves da interface do Github Actions
  workflow_dispatch:

jobs:
  # Job para execucao dos testes
  tests:
    name: TestsRunner
    runs-on: ubuntu-latest
    # Configuracao de passos do nosso job
    steps:
      # 1. Checkout do codigo fonte
      - uses: actions/checkout@v3
      # 2. configurar a JDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      # 3. Executar os testes da aplicacao
      - name: Run application tests
        run: ./mvnw test
